version: '3.8'

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=your_project.settings
      - DJANGO_SECRET_KEY=your-secret-key-here
      # Add other environment variables as needed
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django_app

volumes:
  static_volume:
  media_volume: